services:
    subextractor:
        image: ghcr.io/klementng/subextractor:latest
        container_name: subextractor
        
        user: 1000:1000
        environment:
            - TZ=Etc/UTC
        
        volumes:
            - /path/to/media:/media

        command: >
            /media 
            --log-level INFO
            --app-watch
            --app-scan-interval 10
            --app-enabled-extractor
            --app-enabled-postprocessor
            --extractor-exclude-file ./extracted.txt
            --extractor-exclude-append
            --extractor-extract-bitmap
            --extractor-config-overwrite
            --extractor-config-desired-formats srt,ass
            --extractor-config-languages all
            --extractor-config-unknown-language-as eng
            --postprocessor-exclude-enable ./postprocessed.txt
            --postprocessor-exclude-file ./postprocessed.txt
            --postprocessor-exclude-append
            --postprocessor-config-workflow-file postprocess.yaml
        
        restart: unless-stopped