services:
    subextractor:
        image: ghcr.io/klementng/subextractor:latest
        container_name: subextractor
        user: 1000:1000
        environment:
            - TZ=Etc/UTC
        volumes:
            - /path/to/media:/media
            - /path/to/config/config
        command: >
            /media 
            --log-level INFO
            
            --app-watch
            --app-scan-interval 15
            
            --app-enabled-extractor
            --app-enabled-postprocessor

            --extractor-exclude-enable
            --extractor-exclude-file /config/extracted.txt
            --extractor-exclude-append
            
            --extractor-extract-bitmap
            
            --extractor-config-desired-formats srt ass
            --extractor-config-languages all
            --extractor-config-unknown-language-as eng
            
            --postprocessor-exclude-enable
            --postprocessor-exclude-file /config/postprocessed.txt
            --postprocessor-exclude-append
            
            --postprocessor-config-workflow-file /config/postprocess.yaml
            
        restart: unless-stopped
