services:
    
    test:
        build: .
        command: /media --formats srt ass --languages all --log_level DEBUG
        volumes:
            - ./tests/samples:/media
    
    #sample config
    subtitle-extract:
        image: ghcr.io/klementng/subtitle-extract:main
        container_name: subtitle-extract
        user: 1000:1000
        environment:
            - TZ=Etc/UTC
        volumes:
            - /path/to/media:/media
        command: /media --formats srt ass --languages eng --postprocessing ./postprocess.yml --scan_interval 30
        restart: unless-stopped